            $this->HtmlTable
            (
               "",
               array
               (
                  $this->HtmlList
                  (
                     array
                     (
                        $this->MyActions_Entry("ResendConfirm"),
                        preg_replace
                        (
                           '/ModuleName=Friends&/',
                           "",
                           $this->MyActions_Entry("Logon")
                        ),
                     )
                  )
                  ,
               )
            ).
            "";
