            $this->HtmlTable
            (
               "",
               array
               (
                  $this->HtmlList
                  (
                     array
                     (
                         $this->Htmls_Text($this->MyActions_Entry("ResendConfirm")),
                        preg_replace
                        (
                           '/ModuleName=Friends&/',
                           "",
                           $this->Htmls_Text($this->MyActions_Entry("Logon"))
                        ),
                     )
                  )
                  ,
               )
            ).
            "";
