   "00_Top" => array
   (
      "Admin" => "1",
      "Assessor" => "0",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=Start",
      "Name" => "Início",
      "Name_ES" => "Inicio",
      "Name_UK" => "Start",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Voltar ao Início",
      "Title_ES" => "Inicio",
      "Title_UK" => "Start",
   ),
   "40_Logon" => array
   (
      "Admin" => "0",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=Logon",
      "Name" => "Efetuar Login",
      "Name_ES" => "Efetuar Login",
      "Name_UK" => "Logon",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Efetuar Login",
      "Title_ES" => "Hacer Login",
      "Title_UK" => "Logon",
   ),
   "50_Logoff" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=Logoff",
      "Name" => "Sair",
      "Name_ES" => "Salir",
      "Name_UK" => "Logoff",
      "Person" => "1",
      "Public" => "0",
      "SiDS" => "0",
      "SiPE" => "1",
      "Title" => "Sair do Sistema",
      "Title_ES" => "Salir do Sistema",
      "Title_UK" => "Logoff from the Sistema",
   ),
   "60_NewPassword" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=NewPassword",
      "Name" => "Alterar Senha",
      "Name_ES" => "Cambiar Contraseña",
      "Name_UK" => "Change Password",
      "Person" => "0",
      "Public" => "0",
      "Title" => "Alterar minha Senha",
      "Title_ES" => "Cambiar Contraseña",
      "Title_UK" => "Change my Password",
   ),
   "65_NewLogin" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=NewLogin",
      "Name" => "Alterar Email (Login)",
      "Name_ES" => "Cambiar Email (Login)",
      "Name_UK" => "Change Email (Login)",
      "Person" => "0",
      "Public" => "0",
      "Title" => "Alterar meu Email",
      "Title_ES" => "Alterar Email (Login)",
      "Title_UK" => "Change my Email Email",
   ),
   "70_SU" => array
   (
      "Admin" => "1",
      "Assessor" => "0",
      "Coordinator" => "1",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=SU",
      "Name" => "Trocar Usuário",
      "Name_ES" => "Cambiar Usuário",
      "Name_UK" => "Shift User",
      "Person" => "0",
      "Public" => "0",
      "Title" => "Virar para outro Usuário",
      "Title_ES" => "Turnar Usuário",
      "Title_UK" => "Switch to Another User",
   ),
   "80_MyData" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&ModuleName=Friends&Action=Edit&ID=#LoginID",
      "Name" => "Meus Dados",
      "Name_ES" => "Mis Dados",
      "Name_UK" => "My Personal Info",
      "Person" => "0",
      "Public" => "0",
      "Title" => "Editar Dados do meu Cadastro",
      "Title_ES" => "Editar Mis Dados",
      "Title_UK" => "Edit Registration Data",
   ),
   "90_MyUnit" => array
   (
      "Admin" => "0",
      "Assessor" => "0",
      "Coordinator" => "1",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&ModuleName=Units&Action=Edit",
      "Name" => "Minha Entidade",
      "Name_ES" => "Mi Entidad",
      "Name_UK" => "My Entity",
      "Person" => "0",
      "Public" => "0",
      "Title" => "Editar Dados da Minha Entidade",
      "Title_ES" => "Minha Entidad",
      "Title_UK" => "Edit  Entity Data",
   ),

