   "00_Register" => array
   (
      "Admin" => "0",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=Register",
      "Name" => "Cadastrar-se",
      "Name_ES" => "Registrar-se",
      "Name_UK" => "Register",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Cadastrar-se",
      "Title_ES" => "Registrar-se",
      "Title_UK" => "Register",
   ),
   "10_ResendConfirm" => array
   (
      "Admin" => "0",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=ResendConfirm",
      "Name" => "Reenviar Código de Confirmação",
      "Name_ES" => "Reenviar Código de Confirmación",
      "Name_UK" => "Resend Confirm Code",
      "Person" => "0",
      "Public  " => "1",
      "Title" => "Reenviar Código de Confirmação",
      "Title_ES" => "Reenviar Código de Confirmación",
      "Title_UK" => "Resend Confirm Code",
   ),
   "20_Confirm" => array
   (
      "Admin" => "0",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=Confirm",
      "Name" => "Confirmar Cadastro",
      "Name_ES" => "Confirmar Registro",
      "Name_UK" => "Confirm Registration",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Confirmar Cadastro",
      "Title_ES" => "Confirmar Registro",
      "Title_UK" => "Confirm Registration",
   ),
   "25_ResendConfirm" => array
   (
      "Admin" => "0",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=ResendConfirm",
      "Name" => "Reenviar Cod. de Cadastro",
      "Name_ES" => "Reenviar Cod. de Confirmación",
      "Name_UK" => "Resend Confirm Code",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Reenviar Cod. de Cadastro",
      "Title_ES" => "Reenviar Cod. de Confirmación",
      "Title_UK" => "Resend Confirm Code",
   ),
   "30_Recover" => array
   (
      "Admin" => "0",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=Recover",
      "Name" => "Recuperar Senha",
      "Name_ES" => "Recuperar Contraseña",
      "Name_UK" => "Recover Password",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Recuperar Senha",
      "Title_ES" => "Recuperar Contraseña",
      "Title_UK" => "Recover Password",
   ),

