   "10_Units" => array
   (
      "Admin" => "1",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Href" => "?Action=Start",
      "Name" => "Entidades usando SiVent2",
      "Name_ES" => "Entidades usando SiVent2",
      "Name_UK" => "Entities using Sivent2",
      "Person" => "1",
      "Public" => "1",
      "Title" => "Entidades usando SiVent2 neste Servidor",
      "Title_ES" => "Entidades usando SiVent2",
      "Title_UK" => "Entities using Sivent2 on this Server",
   ),
   "20_Sessions" => array
   (
      "Admin" => "1",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=Sessions",
      "Name" => "Sessões",
      "Name_ES" => "Sessiones",
      "Name_UK" => "Sessions",
      "Person" => "0",
      "Public" => "0",
      "Title" => "Sessões de Login",
      "Title_ES" => "Sessiones de Login",
      "Title_UK" => "Login Sessions",
   ),
   "30_Messages" => array
   (
      "Admin" => "0",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=Messages",
      "Name" => "Mensagens dos Sistema",
      "Name_ES" => "Mensajens del Sistema",
      "Name_UK" => "System Messages",
      "Person" => "0",
      "Public" => "0",
      "Title" => "Gerenciar Mensagens dos Sistema",
      "Title_ES" => "Mensajens del Sistema",
      "Title_UK" => "Manage System Messages",
   ),

