array
(
   'Institution' => 'Universidade Federal de Goiás',
   'Title' => 'Instituto de Matemática e Estatística',
   'Key' => 'Instituto de Matemática e Estatística',
   'Name' => 'Instituto de Matemática e Estatística',
   'Department' => '',
   'Address' => 'Prédio do IME, Campus II (Samambaia)',
   'Area' => 'Itatiaia',
   'ZIP' => '74001-970',
   'City' => 'Goiânia',
   'State' => 'GO',
   'Country' => 'Brasil',
   'Phone' => '(62) 3521-1180',
   'Fax' => '',
   'Url' => 'http://www.mat.ufg.br',
   'Email' => 'siventufg@gmail.com',
   'AdmEmail' => 'sipe.ime.ufg@gmail.com',
   'AdmEmailPassword' => 'Sipe.Ime.2013',
   'CCEmail' => 'sipe.ime.ufg@gmail.com',
   'FromName' => 'SiVent2, Sistema de Gestão de Eventos, IME/UFG',
   'Domain' => 'mat.ufg.br',
   'HtmlIcon1' => 'icons/ufg.svg',
   'HtmlIcon2' => 'icons/ufg.svg',
   'LatexIcon1' => 'icons/ufg.png',
   'LatexIcon2' => 'icons/ufg.png',
);
