array
(
   'PublicInterface' => '1',
   'DataGroupMenusPerLine' => '5',
   'WeekDays' => array
   (
      '2ª',
      '3ª',
      '4ª',
      '5ª',
      '6ª',
      'Sáb.',
      'Dom.',
   ),
   'WeekDaysLong' => array
   (
      '2ª-Feira',
      '3ª-Feira',
      '4ª-Feira',
      '5ª-Feira',
      '6ª-Feira',
      'Sábado',
      'Domingo',
   ),
   'Months' => array
   (
      'Janeiro',
      'Fevereiro',
      'Março',
      'Abril',
      'Maio',
      'Junho',
      'Julho',
      'Agosto',
      'Setembro',
      'Outubro',
      'Novembro',
      'Dezembro',
   ),
   'Months_Short' => array
   (
      'Jan',
      'Fev',
      'Mar',
      'Abr',
      'Mai',
      'Jun',
      'Jul',
      'Ago',
      'Set',
      'Out',
      'Nov',
      'Dez',
   ),
   'States' => array
   (
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahia",
      "Ceará",
      "Distrito Federal",
      "Espírito Santo",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Paraná",
      "Paraíba",
      "Pará",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "Sergipe",
      "São Paulo",
      "Tocantins",
      "Exterior",
      "Dinamarca",
      "Turqúia",
   ),
   'States_Short' => array
   (
      "AC",
      "AL",
      "AP",
      "AM",
      "BA",
      "CF",
      "DF",
      "ES",
      "GO",
      "MA",
      "MT",
      "MS",
      "MG",
      "PN",
      "PB",
      "PA",
      "PE",
      "PI",
      "RJ",
      "RN",
      "RS",
      "RO",
      "RR",
      "SC",
      "SE",
      "SP",
      "TO",
      "EX",
      "DIN",
      "TUR",
   ),
);
