array
(
   "00_Register" => array
   (
      "Admin" => "0",
      "Assessor" => "0",
      "Coordinator" => "0",
      "Friend" => "0",
      "Name" => "Registrar-se:",
      "Name_ES" => "Registrar-se:",
      "Name_UK" => "Register:",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Registrar-se:",
      "Title_ES" => "Registrar-se:",
      "Title_UK" => "Register:",
      "include_file" => "System/LeftMenu/Register.php",
   ),
   "00_Personal" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Name" => "Pessoal:",
      "Name_ES" => "Personal:",
      "Name_UK" => "Personal:",
      "Person" => "1",
      "Public" => "1",
      "Title" => "Pessoal:",
      "Title_ES" => "Personal:",
      "Title_UK" => "Personal:",
      "include_file" => "System/LeftMenu/Personal.php",
   ),
   "01_Sponsors" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Name" => "Patrocinadores:",
      "Name_ES" => "Patrocinadores:",
      "Name_UK" => "Sponsors:",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Patrocinadores:",
      "Title_ES" => "Patrocinadores:",
      "Title_UK" => "Sponsors:",
      "include_file" => "System/LeftMenu/Sponsors.php",
   ),
   "01_Profile" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Method" => "MyApp_Interface_LeftMenu_Profile",
      "Name" => "Perfís:",
      "Name_ES" => "Perfiles:",
      "Name_UK" => "Profiles:",
      "Person" => "0",
      "Public" => "0",
      "Title" => "Perfís:",
      "Title_ES" => "Perfiles:",
      "Title_UK" => "Profiles:",
   ),
   "03_Unit" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Method" => "HtmlUnitMenu",
      "Name" => "Entidade:",
      "Name_ES" => "Entidad:",
      "Name_UK" => "Entity:",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Entidade:",
      "Title_ES" => "Entidad:",
      "Title_UK" => "Entity:",
   ),
   "04_Event" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Method" => "HtmlEventsMenu",
      "Name" => "Eventos:",
      "Name_ES" => "Eventos:",
      "Name_UK" => "Events:",
      "Person" => "0",
      "Public" => "1",
      "Title" => "Eventos:",
      "Title_ES" => "Eventos:",
      "Title_UK" => "Events:",
   ),
   "05_Language" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Method" => "MyApp_Interface_LeftMenu_Language",
      "Name" => "Línguas:",
      "Name_ES" => "Idiomas:",
      "Name_UK" => "Language:",
      "Person" => "1",
      "Public" => "1",
      "Title" => "Línguas:",
      "Title_ES" => "Idiomas:",
      "Title_UK" => "Language:",
   ),
   "06_Units" => array
   (
      "Admin" => "1",
      "Coordinator" => "0",
      "Friend" => "0",
      "Name" => "Entidades:",
      "Name_ES" => "Entidades:",
      "Name_UK" => "Entities:",
      "Person" => "1",
      "Public" => "1",
      "Title" => "Entidades:",
      "Title_ES" => "Entidades:",
      "Title_UK" => "Entities:",
      "include_file" => "System/LeftMenu/System.php",
   ),
);

