   "Logs" => array
   (
      "ItemName" => "Log Entry",
      "ItemName_ES" => "Log Entry",
      "ItemName_UK" => "Log Entry",
      "ItemNamer" => "ID",
      "ItemNamer_UK" => "ID",
      "ItemsName" => "Log Entries",
      "ItemsName_ES" => "Log Entry",
      "ItemsName_UK" => "Log Entries",
      "SqlClass" => "Logs",
      "SqlDerivedData" => array("Message"),
      "SqlFile" => "Logs.php",
      "SqlFilter" => "#Message",
      "SqlHref" => "1",
      "SqlObject" => "LogsObject",
      "SqlTable" => "Logs",
   ),
   "Friends" => array
   (
      "ItemName" => "Usuário",
      "ItemName_ES" => "Usuario",
      "ItemName_UK" => "User",
      "ItemsName" => "Usuários",
      "ItemsName_ES" => "Usuario",
      "ItemsName_UK" => "Users",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlClass" => "Friends",
      "SqlDerivedData" => array("Name","Email"),
      "SqlFile" => "Friends.php",
      "SqlFilter" => "#Name (#Email)",
      "SqlFilter_Public" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "FriendsObject",
      "SqlTable" => "Friends",
   ),
   "Units" => array
   (
      "ItemName" => "Entidade",
      "ItemName_ES" => "Entidad",
      "ItemName_UK" => "Entity",
      "ItemsName" => "Entidades",
      "ItemsName_ES" => "Entidades",
      "ItemsName_UK" => "Entities",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "UnitsObj",
      "SqlClass" => "Units",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Units.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "UnitsObject",
      "SqlTable" => "Units",
   ),
   "MailTypes" => array
   (
      "ItemName" => "Email Tipo",
      "ItemName_ES" => "Email Tipo",
      "ItemName_UK" => "Email Type",
      "ItemsName" => "Email Tipos",
      "ItemsName_ES" => "Email Tipos",
      "ItemsName_UK" => "Email Types",
      "ItemsNamer" => "Name",
      "SqlAccessor" => "MailTypesObj",
      "SqlClass" => "MailTypes",
      "SqlDerivedData" => array("Name","Language"),
      "SqlFile" => "MailTypes.php",
      "SqlFilter" => "#Name #Language",
      "SqlHref" => "1",
      "SqlObject" => "MailTypesObject",
      "SqlTable" => "MailTypes",
   ),
   "Events" => array
   (
      "ItemName" => "Evento",
      "ItemName_ES" => "Evento",
      "ItemName_UK" => "Event",
      "ItemsName" => "Eventos",
      "ItemsName_ES" => "Evento",
      "ItemsName_UK" => "Events",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name_UK",
      "SqlAccessor" => "EventsObj",
      "SqlClass" => "Events",
      "SqlDerivedData" => array("Name","Unit"),
      "SqlFile" => "Events.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "EventsObject",
      "SqlTable" => "#Unit__Events",
   ),
   "Datas" => array
   (
      "ItemName" => "Dado, Questionário",
      "ItemName_ES" => "Dado, Questionário",
      "ItemName_UK" => "Data, Questionary",
      "ItemsName" => "Dados, Questionário",
      "ItemsName_ES" => "Dado, Questionário",
      "ItemsName_UK" => "Data, Questionary",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "DatasObj",
      "SqlClass" => "Datas",
      "SqlDerivedData" => array("SqlKey","Event"),
      "SqlFile" => "Datas.php",
      "SqlFilter" => "#SqlKey",
      "SqlHref" => "1",
      "SqlObject" => "DatasObject",
      "SqlTable" => "#Unit__Datas",
   ),
   "GroupDatas" => array
   (
      "ItemName" => "Grupo, Questionário",
      "ItemName_ES" => "Grupo, Questionário",
      "ItemName_UK" => "Group, Questionary",
      "ItemsName" => "Grupos, Questionário",
      "ItemsName_ES" => "Grupo, Questionário",
      "ItemsName_UK" => "Groups, Questionary",
      "ItemsNamer" => "Text",
      "ItemsNamer_UK" => "Text",
      "SqlAccessor" => "GroupDatasObj",
      "SqlClass" => "GroupDatas",
      "SqlDerivedData" => array("Text","Event"),
      "SqlFile" => "GroupDatas.php",
      "SqlFilter" => "#Text",
      "SqlHref" => "1",
      "SqlObject" => "GroupDatasObject",
      "SqlTable" => "#Unit__GroupDatas",
   ),
   "Inscriptions" => array
   (
      "ItemName" => "Inscrição",
      "ItemName_ES" => "Inscrición",
      "ItemName_UK" => "Inscription",
      "ItemsName" => "Inscrições",
      "ItemsName_ES" => "Inscriciones",
      "ItemsName_UK" => "Inscriptions",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "InscriptionsObj",
      "SqlClass" => "Inscriptions",
      "SqlDerivedData" => array("Friend","Event"),
      "SqlFile" => "Inscriptions.php",
      "SqlFilter" => "#Friend",
      "SqlHref" => "1",
      "SqlObject" => "InscriptionsObject",
      "SqlTable" => "#Unit__#Event_Inscriptions",
   ),
   "Sponsors" => array
   (
      "ItemName" => "Patrocinador",
      "ItemName_ES" => "Patrocinador",
      "ItemName_UK" => "Sponsor",
      "ItemsName" => "Patrocinadores",
      "ItemsName_ES" => "Patrocinadores",
      "ItemsName_UK" => "Sponsors",
      "ItemsNamer" => "Initials",
      "ItemsNamer_UK" => "Initials",
      "SqlAccessor" => "SponsorsObj",
      "SqlClass" => "Sponsors",
      "SqlDerivedData" => array("Initials","Name"),
      "SqlFile" => "Sponsors.php",
      "SqlFilter" => "#Initials - #Name",
      "SqlHref" => "1",
      "SqlObject" => "SponsorsObject",
      "SqlTable" => "#Unit__Sponsors",
   ),
   "Permissions" => array
   (
      "ItemName" => "Permissão",
      "ItemName_ES" => "Permiso",
      "ItemName_UK" => "Permission",
      "ItemsName" => "Permissões",
      "ItemsName_ES" => "Permisos",
      "ItemsName_UK" => "Permissions",
      "ItemsNamer" => "ID",
      "ItemsNamer_UK" => "ID",
      "SqlAccessor" => "PermissionsObj",
      "SqlClass" => "Permissions",
      "SqlDerivedData" => array("ID","Event"),
      "SqlFile" => "Permissions.php",
      "SqlFilter" => "#ID #Event",
      "SqlHref" => "1",
      "SqlObject" => "PermissionsObject",
      "SqlTable" => "#Unit__Permissions",
   ),
   "Collaborations" => array
   (
      "ItemName" => "Colaboração",
      "ItemName_ES" => "Colaboración",
      "ItemName_UK" => "Collaboration",
      "ItemsName" => "Colaborações",
      "ItemsName_ES" => "Colaboraciones",
      "ItemsName_UK" => "Collaborations",
      "ItemsNamer" => "ID",
      "ItemsNamer_UK" => "ID",
      "SqlAccessor" => "CollaborationsObj",
      "SqlClass" => "Collaborations",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Collaborations.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "CollaborationsObject",
      "SqlTable" => "#Unit__#Event_Collaborations",
   ),
   "Collaborators" => array
   (
      "ItemName" => "Colaborador",
      "ItemName_ES" => "Contribuyente",
      "ItemName_UK" => "Collaborator",
      "ItemsName" => "Colaboradores",
      "ItemsName_ES" => "Contribuyentes",
      "ItemsName_UK" => "Collaborators",
      "ItemsNamer" => "ID",
      "ItemsNamer_UK" => "ID",
      "SqlAccessor" => "CollaboratorsObj",
      "SqlClass" => "Collaborators",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Collaborators.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "CollaboratorsObject",
      "SqlTable" => "#Unit__#Event_Collaborators",
   ),
   "Caravaneers" => array
   (
      "ItemName" => "Caravaneiro(a)",
      "ItemName_ES" => "Caravaneiro(a)",
      "ItemName_UK" => "Caravaneer",
      "ItemsName" => "Caravaneiro(a)s",
      "ItemsName_ES" => "Caravaneiro(a)",
      "ItemsName_UK" => "Caravaneers",
      "ItemsNamer" => "ID",
      "ItemsNamer_UK" => "ID",
      "SqlAccessor" => "CaravaneersObj",
      "SqlClass" => "Caravaneers",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Caravaneers.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "CaravaneersObject",
      "SqlTable" => "#Unit__#Event_Caravaneers",
   ),
   "Caravans" => array
   (
      "ItemName" => "Caravana",
      "ItemName_ES" => "Caravana",
      "ItemName_UK" => "Caravan",
      "ItemsName" => "Caravanas",
      "ItemsName_ES" => "Caravana",
      "ItemsName_UK" => "Caravans",
      "ItemsNamer" => "ID",
      "ItemsNamer_UK" => "ID",
      "SqlAccessor" => "CaravansObj",
      "SqlClass" => "Caravans",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Caravans.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "CaravansObject",
      "SqlTable" => "#Unit__#Event_Inscriptions",
   ),
   "Submissions" => array
   (
      "ItemName" => "Atividade",
      "ItemName_ES" => "Atividad",
      "ItemName_UK" => "Activity",
      "ItemsName" => "Atividades",
      "ItemsName_ES" => "Atividades",
      "ItemsName_UK" => "Activities",
      "ItemsNamer" => "Title",
      "ItemsNamer_UK" => "Title_UK",
      "SqlAccessor" => "SubmissionsObj",
      "SqlClass" => "Submissions",
      "SqlDerivedData" => array("Name","Title"),
      "SqlFile" => "Submissions.php",
      "SqlFilter" => "#Name: #Title",
      "SqlHref" => "1",
      "SqlObject" => "SubmissionsObject",
      "SqlTable" => "#Unit__#Event_Submissions",
   ),
   "Areas" => array
   (
      "ItemName" => "Área de Interesse",
      "ItemName_ES" => "Área de Interés",
      "ItemName_UK" => "Area of Interest",
      "ItemsName" => "Áreas de Interesse",
      "ItemsName_ES" => "Áreas de Interés",
      "ItemsName_UK" => "Areas of Interest",
      "ItemsNamer" => "Title",
      "ItemsNamer_UK" => "Title_UK",
      "SqlAccessor" => "AreasObj",
      "SqlClass" => "Areas",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Areas.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "AreasObject",
      "SqlTable" => "#Unit__#Event_Areas",
   ),
   "Certificates" => array
   (
      "ItemName" => "Certificado",
      "ItemName_ES" => "Certificado",
      "ItemName_UK" => "Certificate",
      "ItemsName" => "Certificados",
      "ItemsName_ES" => "Certificado",
      "ItemsName_UK" => "Certificates",
      "ItemsNamer" => "Code",
      "ItemsNamer_UK" => "Code",
      "SqlAccessor" => "CertificatesObj",
      "SqlClass" => "Certificates",
      "SqlDerivedData" => array("Code","Name"),
      "SqlFile" => "Certificates.php",
      "SqlFilter" => "#Code, #Name",
      "SqlHref" => "1",
      "SqlObject" => "CertificatesObject",
      "SqlTable" => "#Unit__Certificates",
   ),
   "Dates" => array
   (
      "ItemName" => "Data",
      "ItemName_ES" => "Data",
      "ItemName_UK" => "Date",
      "ItemsName" => "Datas",
      "ItemsName_ES" => "Data",
      "ItemsName_UK" => "Dates",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "DatesObj",
      "SqlClass" => "Dates",
      "SqlDerivedData" => array("Name","Title"),
      "SqlFile" => "Dates.php",
      "SqlFilter" => "#Title",
      "SqlHref" => "1",
      "SqlObject" => "DatesObject",
      "SqlTable" => "#Unit__#Event_Dates",
   ),
   "Times" => array
   (
      "ItemName" => "Horário",
      "ItemName_ES" => "Horario",
      "ItemName_UK" => "Time Slot",
      "ItemsName" => "Horários",
      "ItemsName_ES" => "Horario",
      "ItemsName_UK" => "Time Slots",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "TimesObj",
      "SqlClass" => "Times",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Times.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "TimesObject",
      "SqlTable" => "#Unit__#Event_Times",
   ),
   "Places" => array
   (
      "ItemName" => "Local",
      "ItemName_ES" => "Local",
      "ItemName_UK" => "Place",
      "ItemsName" => "Locais",
      "ItemsName_ES" => "Local",
      "ItemsName_UK" => "Places",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "PlacesObj",
      "SqlClass" => "Places",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Places.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "PlacesObject",
      "SqlTable" => "#Unit__#Event_Places",
   ),
   "Rooms" => array
   (
      "ItemName" => "Sala",
      "ItemName_ES" => "Sala",
      "ItemName_UK" => "Room",
      "ItemsName" => "Salas",
      "ItemsName_ES" => "Salas",
      "ItemsName_UK" => "Rooms",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "RoomsObj",
      "SqlClass" => "Rooms",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Rooms.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "RoomsObject",
      "SqlTable" => "#Unit__#Event_Rooms",
   ),
   "Schedules" => array
   (
      "ItemName" => "Slot",
      "ItemName_ES" => "Slot",
      "ItemName_UK" => "Slot",
      "ItemsName" => "Slots",
      "ItemsName_ES" => "Slots",
      "ItemsName_UK" => "Slots",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "SchedulesObj",
      "SqlClass" => "Schedules",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Schedules.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "SchedulesObject",
      "SqlTable" => "#Unit__Schedules",
   ),
   "Speakers" => array
   (
      "ItemName" => "Palestrante",
      "ItemName_ES" => "Palestrante",
      "ItemName_UK" => "Speaker",
      "ItemsName" => "Palestrantes",
      "ItemsName_ES" => "Palestrantes",
      "ItemsName_UK" => "Speakers",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "SpeakersObj",
      "SqlClass" => "Speakers",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Speakers.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "SpeakersObject",
      "SqlTable" => "#Unit__#Event_Speakers",
   ),
   "PreInscriptions" => array
   (
      "ItemName" => "Preinscrição",
      "ItemName_ES" => "Preinscrición",
      "ItemName_UK" => "Preinscription",
      "ItemsName" => "Preinscrições",
      "ItemsName_ES" => "Preinscriciones",
      "ItemsName_UK" => "Preinscriptions",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "PreInscriptionsObj",
      "SqlClass" => "PreInscriptions",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "PreInscriptions.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "PreInscriptionsObject",
      "SqlTable" => "#Unit__#Event_PreInscriptions",
   ),
   "Presences" => array
   (
      "ItemName" => "Presença",
      "ItemName_ES" => "Presencia",
      "ItemName_UK" => "Presence",
      "ItemsName" => "Presenças",
      "ItemsName_ES" => "Presencias",
      "ItemsName_UK" => "Presences",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "PresencesObj",
      "SqlClass" => "Presences",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Presences.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "PresencesObject",
      "SqlTable" => "#Unit__#Event_Presences",
   ),
   "Criterias" => array
   (
      "ItemName" => "Critério",
      "ItemName_ES" => "Critério",
      "ItemName_UK" => "Criteria",
      "ItemsName" => "Critério",
      "ItemsName_ES" => "Critérios",
      "ItemsName_UK" => "Criterias",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "CriteriasObj",
      "SqlClass" => "Criterias",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Criterias.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "CriteriasObject",
      "SqlTable" => "#Unit__#Event_Criterias",
   ),
   "Assessors" => array
   (
      "ItemName" => "Avaliador",
      "ItemName_ES" => "Tasador",
      "ItemName_UK" => "Assessor",
      "ItemsName" => "Avaliadores",
      "ItemsName_ES" => "Tasadores",
      "ItemsName_UK" => "Assessors",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "AssessorsObj",
      "SqlClass" => "Assessors",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Assessors.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "AssessorsObject",
      "SqlTable" => "#Unit__#Event_Assessors",
   ),
   "Assessments" => array
   (
      "ItemName" => "Avaliação",
      "ItemName_ES" => "Evaluación",
      "ItemName_UK" => "Assessment",
      "ItemsName" => "Avaliações",
      "ItemsName_ES" => "Evaluaciones",
      "ItemsName_UK" => "Assessments",
      "ItemsNamer" => "Name",
      "ItemsNamer_UK" => "Name",
      "SqlAccessor" => "AssessmentsObj",
      "SqlClass" => "Assessments",
      "SqlDerivedData" => array("Name"),
      "SqlFile" => "Assessments.php",
      "SqlFilter" => "#Name",
      "SqlHref" => "1",
      "SqlObject" => "AssessmentsObject",
      "SqlTable" => "#Unit__#Event_Assessments",
   ),

