array
(
   "Certificates_Validation_Form_Title" => array
   (
      "Name" => "Validar Certificados Emitidos por Sivent2",
      "Name_ES" => "Validar Certificados Emitidos por Sivent2",
      "Name_UK" => "Validate Certificates Emitted by Sivent2",
      "Title" => "Validar Certificados Emitidos por Sivent2",
      "Title_ES" => "Validar Certificados Emitidos por Sivent2",
      "Title_UK" => "Validate Certificates Emitted by Sivent2",
   ),
   "Certificates_Validation_Form_Code_Title" => array
   (
      "Name" => "Código de Verificação",
      "Name_ES" => "Código de Verificación",
      "Name_UK" => "Validation Code",
      "Title" => "Código de Verificação",
      "Title_ES" => "Código de Verificación",
      "Title_UK" => "Validation Code",
   ),
   "Certificates_Validation_Form_Button_Title" => array
   (
      "Name" => "Validar",
      "Name_ES" => "Validar",
      "Name_UK" => "Validate",
      "Title" => "Validar",
      "Title_ES" => "Validar",
      "Title_UK" => "Validate",
   ),
   "Certificates_Validation_Table_Title" => array
   (
      "Name" => "Validação do Código",
      "Name_ES" => "Validación do Código",
      "Name_UK" => "Validation of Code",
      "Title" => "Validação do Código",
      "Title_ES" => "Validación do Código",
      "Title_UK" => "Validation of Code",
   ),
   "Certificates_Validation_Table_Empty" => array
   (
      "Name" => "Código de Validação Desconhecido.",
      "Name_ES" => "Código de Validación Desconecido.",
      "Name_UK" => "Unknown Validation Code",
      "Title" => "Código de Validação Desconhecido.",
      "Title_ES" => "Código de Validación Desconecido.",
      "Title_UK" => "Unknown Validation Code",
   ),
   "Certificates_Validation_Empty" => array
   (
      "Name" => "Código de Validação Inválido.",
      "Name_ES" => "Código de Validación Inválido.",
      "Name_UK" => "Invalid Validation Code",
      "Title" => "Código de Validação Inválido.",
      "Title_ES" => "Código de Validación Inválido.",
      "Title_UK" => "Invalid Validation Code",
   ),
   "Certificates_Validation_Message1" => array
   (
      "Name" => "Este certificado foi gerado pelo Sivent2 e possui código de verificação",
      "Name_ES" => "Este certificado foi gerado pelo Sivent2 e possui código de verificación",
      "Name_UK" => "This certificate was generated by Sivent2 and has a verification code",
      "Title" => "Este certificado foi gerado pelo Sivent2 e possui código de verificação",
      "Title_ES" => "Este certificado foi gerado pelo Sivent2 e possui código de verificación",
      "Title_UK" => "This certificate was generated by Sivent2 and has a verification code",
   ),
   "Certificates_Validation_Message2" => array
   (
      "Name" => "Para Verificar, acesse",
      "Name_ES" => "Para Verificar, acesse",
      "Name_UK" => "Verify accessing",
      "Title" => "Para Verificar, acesse",
      "Title_ES" => "Para Verificar, acesse",
      "Title_UK" => "Verify accessing",
   ),
   "Certificate_Link" => array
   (
      "Name" => "Gerar Certificados",
      "Name_ES" => "Gerar Certificados",
      "Name_UK" => "Generate Certificates",
      "Title" => "Gerar Certificados",
      "Title_ES" => "Gerar Certificados",
      "Title_UK" => "Generate Certificates",
   ),
   "Certificate_Not_Available_Yet" => array
   (
      "Name" => "Certificados Aguardando Liberação",
      "Name_ES" => "Certificados Aguardando Liberación",
      "Name_UK" => "Certificates Awaiting Liberation",
      "Title" => "Certificados Aguardando Liberação",
      "Title_ES" => "Certificados Aguardando Liberación",
      "Title_UK" => "Certificates Awaiting Liberation",
   ),
   "Certificate_Friend_Table_Title" => array
   (
      "Name" => "Meus Certificados",
      "Name_ES" => "Mis Certificados",
      "Name_UK" => "My Certificates",
      "Title" => "Meus Certificados",
      "Title_ES" => "Mis Certificados",
      "Title_UK" => "My Certificates",
   ),
);

