array
(
   "Certificates_Validation_Form_Title" => array
   (
      "Name" => "Validar Certificados Emitidos por Sivent2",
      "Name_UK" => "Validate Certificates Emitted by Sivent2",
   ),
   "Certificates_Validation_Form_Code_Title" => array
   (
      "Name" => "Código de Verificação",
      "Name_UK" => "Validation Code",
   ),
   "Certificates_Validation_Form_Button_Title" => array
   (
      "Name" => "Validar",
      "Name_UK" => "Validate",
   ),
   "Certificates_Validation_Table_Title" => array
   (
      "Name" => "Validação do Código",
      "Name_UK" => "Validation of Code",
   ),
   "Certificates_Validation_Table_Empty" => array
   (
      "Name" => "Código de Validação Desconhecido.",
      "Name_UK" => "Unknown Validation Code",
   ),
   "Certificates_Validation_Empty" => array
   (
      "Name" => "Código de Validação Inválido.",
      "Name_UK" => "Invalid Validation Code",
   ),
   "Certificates_Validation_Message1" => array
   (
      "Name" => "Este certificado foi gerado pelo Sivent2 e possui código de verificação",
      "Name_UK" => "This certificate was generated by Sivent2 and has a verification code",
   ),
   "Certificates_Validation_Message2" => array
   (
      "Name" => "Para Verificar, acesse",
      "Name_UK" => "Verify accessing",
   ),
   "Certificate_Link" => array
   (
      "Name" => "Gerar Certificados",
      "Name_UK" => "Generate Certificates",
   ),
   "Certificate_Not_Available_Yet" => array
   (
      "Name" => "Certificados Aguardando Liberação",
      "Name_UK" => "Certificates Awaiting Liberation",
   ),
);
