array
(
   "Status" => array
   (
      "Name" => "Status",
      "ShortName" => "Status",
      "Title" => "Status",
      
      "Sql" => "ENUM",
      "Values" => array("Aguardando Início das Inscrições","Inscrições Abertas","Inscrições Encerradas"),
      "Values_UK" => array("Awaiting Inscriptions to Open","Inscriptions Open","Inscriptions Closed"),
      "Values_ES" => array("Aguardando Inicio de las Inscriciones","Inscriciones Abiertas","Inscriciones Encerradas"),
      "SearchDefault"   => 0,
      "Default"   => 2,
      "Public"   => 1,
      "Person"   => 1,
      "Admin"    => 1,
      "Friend"     => 1,
      "Coordinator" => 1,
      "Assessor"  => 1,
      "Search"  => TRUE,
      "SearchCheckBox"  => FALSE,
   ),
    "Visible" => array
   (
      "Name" => "Visível",
      "Name_UK" => "Visible",

      "Sql" => "ENUM",
      "Values" => array("Sim","Não"),
      "Values_UK" => array("Yes","No"),
      "Default" => 1,
      
      "Public"   => 1,
      "Person"   => 0,
      "Admin"    => 2,
      "Friend" => 0,
      "Coordinator" => 1,
      
      "Default" => 1,
      "Compulsory" => FALSE,
      "Search" => FALSE,
      "Compulsory"  => FALSE,
   ),
   
   "EventStart" => array
   (
      "Name" => "Início do Evento",
      "ShortName" => "Início",
      "Title" => "Data Início do Evento",
      
      "Name_UK" => "Event Start",
      "ShortName_UK" => "Start",
      "Title_UK" => "Event Start Date",
      "Sql" => "INT",
      "Public"   => 1,
      "Person"   => 0,
      "Admin"    => 2,
      "Friend" => 1,
      "Coordinator" => 2,
      
      "Compulsory" => 1,
      "Search" => FALSE,
      "Compulsory"  => TRUE,
      "IsDate"  => TRUE,
   ),
   "EventEnd" => array
   (
      "Name" => "Fim do Evento",
      "ShortName" => "Fim",
      "Title" => "Data Fim do Evento",
      
      "Name_UK" => "Event End",
      "ShortName_UK" => "End",
      "Title_UK" => "Event End Date",
      "Sql" => "INT",
      "Public"   => 1,
      "Person"   => 0,
      "Admin"    => 2,
      "Friend" => 1,
      "Coordinator" => 2,
      
      "Compulsory" => 1,
      "Search" => FALSE,
      "Compulsory"  => TRUE,
      "IsDate"  => TRUE,
   ),
   "Place" => array
   (
      "Name" => "Local do Evento",
      "Name_UK" => "Place where Event Occurs",

      "Sql" => "VARCHAR(256)",
      "Size" => 50,

      "Search" => FALSE,

      "Public"   => 1,
      "Person"   => 0,
      "Admin"    => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Assessor"  => 0,
      "Compulsory"  => TRUE,
   ),
   "Place_Address" => array
   (
      "Name" => "Endereço do Local",
      "Name_UK" => "Place Address",

      "Sql" => "VARCHAR(256)",
      "Size" => 50,

      "Search" => FALSE,

      "Public"   => 1,
      "Person"   => 0,
      "Admin"    => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Assessor"  => 0,
      "Compulsory"  => TRUE,
   ),
   "Place_Site" => array
   (
      "Name" => "Site do Local",
      "Name_UK" => "Place Site",

      "Sql" => "VARCHAR(256)",
      "Size" => 50,

      "Search" => FALSE,

      "Public"   => 1,
      "Person"   => 0,
      "Admin"    => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Assessor"  => 0,
      "Compulsory"  => TRUE,
      "Iconify"  => TRUE,
   ),
   "Info" => array
   (
      "Name" => "Informações",
      "Name_UK" => "Informations",
      "Sql" => "TEXT",
      "Size" => "50x10",

      "Public"   => 1,
      "Person"   => 1,
      "Admin"    => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Assessor"  => 1,
      "Search"  => FALSE,
   ),
   "Schedule_Public" => array
   (
      "Name" => "Grade Publicado",
      "Name_UK" => "Schedule Public",
      "SelectCheckBoxes"  => 2,

      "Sql" => "ENUM",
      "Values" => array("Não","Sim"),
      "Values_UK" => array("No","Yes"),
      "Default" => 1,
      
      "Public"   => 1,
      "Person"   => 0,
      "Admin"    => 2,
      "Friend" => 1,
      "Coordinator" => 2,
      
      "Default" => 1,
      "Compulsory" => FALSE,
      "Search" => FALSE,
      "Compulsory"  => FALSE,
   ),
   
   "HtmlIcon1" => array
   (
      "Admin" => 2,
      "Coordinator" => 2,
      "Extensions" => array("jpg","png"),
      "Iconify" => 1,
      "Name" => "Banner(HTML)",
      "Name_ES" => "Banner (HTML)",
      "Name_UK" => "Banner (HTML)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Banner",
      "ShortName_ES" => "Banner",
      "ShortName_UK" => "Banner ",
      "Size" => "25",
      "Sql" => "FILE",
      "Title" => "Banner (HTML)",
      "Title_ES" => "Banner (HTML)",
      "Title_UK" => "Banner (HTML)",
   ),
   "HtmlIcon1_Width" => array
   (
      "Admin" => 2,
      "Coordinator" => 2,
      "Name" => "Banner, Largura (HTML)",
      "Name_ES" => "Banner, Largura  (HTML)",
      "Name_UK" => "Banner, Width (HTML)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Banner, Largura",
      "ShortName_ES" => "Banner, Largura",
      "ShortName_UK" => "Banner, Width",
      "Size" => "5",
      "Sql" => "VARCHAR(16)",
      "Title" => "Banner (HTML)",
      "Title_ES" => "Banner, Largura   (HTML)",
      "Title_UK" => "Banner, Width (HTML)",
      "Default" => "100%",
   ),
   "HtmlIcon1_Height" => array
   (
      "Admin" => 2,
      "Coordinator" => 2,
      "Name" => "Banner, Altura (HTML)",
      "Name_ES" => "Banner, Altura  (HTML)",
      "Name_UK" => "Banner, Height (HTML)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Banner, Altura",
      "ShortName_ES" => "Banner, Altura",
      "ShortName_UK" => "Banner, Height",
      "Size" => "5",
      "Sql" => "VARCHAR(16)",
      "Title" => "Banner, Altura (HTML)",
      "Title_ES" => "Banner, Altura (HTML)",
      "Title_UK" => "Banner, Height (HTML)",
      "Default" => "100px",
   ),
   "HtmlIcon2" => array
   (
      "Admin" => 2,
      "Coordinator" => 2,
      "Extensions" => array("jpg","png"),
      "Iconify" => 1,
      "Name" => "Logotipo do Evento(HTML)",
      "Name_ES" => "Logotipo del Evento (HTML)",
      "Name_UK" => "Event Logo (HTML)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Logotipo  do Evento",
      "ShortName_ES" => "Logotipo del Evento (HTML)",
      "ShortName_UK" => "Event Logo (HTML)",
      "Size" => "25",
      "Sql" => "FILE",
      "Title" => "Logotipo do Evento (HTML)",
      "Title_ES" => "Logotipo (HTML)",
      "Title_UK" => "Event Logo (HTML)",
   ),

   "HtmlIcon2_Width" => array
   (
      "Admin" => 2,
      "Coordinator" => 2,
      "Name" => "Logotipo, Largura (HTML)",
      "Name_ES" => "Logotipo, Largura  (HTML)",
      "Name_UK" => "Logo, Width (HTML)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Logotipo, Largura",
      "ShortName_ES" => "Logotipo, Largura",
      "ShortName_UK" => "Logo, Width",
      "Size" => "5",
      "Sql" => "VARCHAR(16)",
      "Title" => "Logotipo, Largura (HTML)",
      "Title_ES" => "Logotipo, Largura   (HTML)",
      "Title_UK" => "Logo, Width (HTML)",
      "Default" => "75px",
   ),
   "HtmlIcon2_Height" => array
   (
      "Admin" => 2,
      "Coordinator" => 2,
      "Name" => "Logotipo, Altura (HTML)",
      "Name_ES" => "Logotipo, Altura  (HTML)",
      "Name_UK" => "Logo, Height (HTML)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Logotipo, Altura",
      "ShortName_ES" => "Logotipo, Altura",
      "ShortName_UK" => "Logo, Height",
      "Size" => "5",
      "Sql" => "VARCHAR(16)",
      "Title" => "Logotipo, Altura (HTML)",
      "Title_ES" => "Logotipo, Altura (HTML)",
      "Title_UK" => "Logo, Height (HTML)",
      "Default" => "75px",
   ),
);
