array
(
   "Certificate" => array
   (
      "Admin" => "2",
      "Assessor" => "0",
      "Coordinator" => "2",
      "Default" => "1",
      "Friend" => "1",
      "Name" => "Certificado Liberado",
      "Name_ES" => "Certificado Liberado",
      "Name_UK" => "Certificate Published",
      "Person" => "0",
      "Public" => "1",
      "Search" => "",
      "SelectCheckBoxes" => "2",
      "ShortName" => "Certificado Liberado",
      "ShortName_ES" => "Certificado Liberado",
      "ShortName_UK" => "Certificate Published",
      "Sql" => "ENUM",
      "SubAction" => "Certificates",
      "Title" => "Certificado Liberado",
      "Title_ES" => "Certificado Liberado",
      "Title_UK" => "Certificate Published",
      "Values" => array("Não","Sim"),
      "Values_UK" => array("No","Yes"),
   ),
   "Certificate_CH" => array
   (
      "Admin" => "2",
      "Assessor" => "0",
      "Coordinator" => "2",
      "Friend" => "1",
      "Name" => "Certificado CH",
      "Name_ES" => "Certificado CH",
      "Name_UK" => "Certificate TimeLoad",
      "Person" => "0",
      "Public" => "1",
      "Regexp" => "^\d+$",
      "Search" => "",
      "ShortName" => "CH",
      "ShortName_ES" => "CH",
      "ShortName_UK" => "TimeLoad",
      "Size" => "2",
      "Sql" => "VARCHAR(8)",
      "Title" => "Certificado Carga Horário",
      "Title_ES" => "Certificado Carga Horaria",
      "Title_UK" => "Certificate TimeLoad",
   ),
);

