array
(
   "Basic" => array
   (
      "Admin" => "1",
      "Coordinator" => "1",
      "Data" => array("No","Edit","Delete","GenCert","MailCert","Event","Friend","Status","Inscription","Code"),
      "Friend" => "1",
      "Name" => "Básicos",
      "Name_ES" => "Básicos",
      "Name_UK" => "Basic",
      "Person" => "0",
      "Public" => "0",
      "ShortName" => "Básicos",
      "ShortName_ES" => "Básicos",
      "ShortName_UK" => "Basic",
      "Title" => "Básicos",
      "Title_ES" => "Básicos",
      "Title_UK" => "Basic",
   ),
   "Timess" => array
   (
      "Admin" => "1",
      "Coordinator" => "1",
      "Data" => array("No","Edit","Delete","GenCert","MailCert","Event","Friend","Status","CTime","MTime","ATime","Inscription","Code"),
      "Friend" => "1",
      "Name" => "Tempos",
      "Name_ES" => "Tiempos",
      "Name_UK" => "Times",
      "Person" => "0",
      "Public" => "0",
      "ShortName" => "Tempos",
      "ShortName_ES" => "Tiempos",
      "ShortName_UK" => "Times",
      "Title" => "Tempos",
      "Title_ES" => "Tiempos",
      "Title_UK" => "Times",
   ),
   "Selection" => array
   (
      "Admin" => "1",
      "Assessor" => "0",
      "Coordinator" => "1",
      "Data" => array("No","Edit","Delete","Event","Friend","Status","Selected","Code"),
      "Edit_Admin" => "1",
      "Edit_Coordinator" => "1",
      "Friend" => "1",
      "Name" => "Seleção",
      "Name_ES" => "Seleción",
      "Name_UK" => "Selection",
      "Person" => "0",
      "Public" => "1",
      "ShortName" => "Seleção",
      "ShortName_ES" => "Seleción",
      "ShortName_UK" => "Selection",
      "Title" => "Seleção",
      "Title_ES" => "Seleción",
      "Title_UK" => "Selection",
   ),
   "Certificates" => array
   (
      "Admin" => "1",
      "Assessor" => "0",
      "Coordinator" => "1",
      "Data" => array("No","Edit","Delete","Event","Friend","Status","Selected","Certificate","Certificate_CH","Inscription_Certificate_Generated_Cell","GenCert","Inscription_Certificate_Mailed_Cell","MailCert","Code"),
      "Edit_Admin" => "1",
      "Edit_Coordinator" => "1",
      "Friend" => "1",
      "Name" => "Certificados",
      "Name_ES" => "Certificados",
      "Name_UK" => "Certificates",
      "Person" => "0",
      "Public" => "1",
      "ShortName" => "Certificados",
      "ShortName_ES" => "Certificados",
      "ShortName_UK" => "Certificates",
      "Title" => "Certificados",
      "Title_ES" => "Certificados",
      "Title_UK" => "Certificates",
   ),
);

