array
(
     "Event" => array
     (
        "Href"     => "",
        "HrefArgs" => "?ModuleName=Events&Action=Show&Event=".$this->Event("ID"),
        "Title"    => "Gerenciar Evento",
        "Title_UK" => "Manage Event",
        "Name"     => "Evento",
        "Name_UK"     => "Event",

        "Public"   => 0,
        "Person"   => 0,
        "Admin"    => 1,
        "Friend"   => 0,
        "Coordinator"   => 1,
        "Advisor"    => 0,
        'AccessMethod'    => "Current_User_Event_May_Edit",
      ),
    "Submission" => array
     (
        "Href"     => "",
        "HrefArgs" => "?ModuleName=Submissions&Action=Details&Event=#Event&ID=#Submission",
        "Title"    => "Detalhes da Atividade",
        "Title_UK" => "Submission Details",
        "Name"     => "Detalhes",
        "Name_UK"     => "Details",

        "Public"   => 1,
        "Person"   => 0,
        "Admin"    => 1,
        "Friend"   => 1,
        "Coordinator"   => 1,
        "Advisor"    => 0,
        'AccessMethod'    => "Current_User_Event_Submissions_May_Show",
      ),

     "Datas" => array
     (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Events&Action=Datas",
        "Name"    => "Question&aacute;rio",
        "Name_UK"     => "Questionary",
        "Public"   => 1,
        "Person"   => 1,
        "Admin"   => 1,
        "Distributor"   => 1,
        "Coordinator"   => 1,
        "Teacher"   => 1,
        "Handler"   => "",
        "AccessMethod"   => "Coordinator_Inscriptions_Access_Has",
      ),
     "DataGroups" => array
     (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Events&Action=DataGroups",
        "Name"    => "Grupos do Question&aacute;rio",
        "Name_UK"     => "Questionary Groups",
        "Public"   => 1,
        "Person"   => 1,
        "Admin"   => 1,
        "Distributor"   => 1,
        "Coordinator"   => 1,
        "Teacher"   => 1,
        "Handler"   => "",
        "AccessMethod"   => "Coordinator_Inscriptions_Access_Has",
      ),
     "RegDatas" => array
     (
        "Href"     => "",
        "HrefArgs" => "ModuleName=RegDatas&Action=EditList",
        "Name"    => "Dados Vis&iacute;veis do Cadastro",
        "Name_UK"     => "Visible Registration Data",
        "Title"    => "Dados Vis&iacute;veis do Cadastro",
        "Title_UK"     => "Visible Registration Data",
        "Public"   => 1,
        "Person"   => 1,
        "Admin"   => 1,
        "Distributor"   => 1,
        "Coordinator"   => 1,
        "Teacher"   => 1,
        "Handler"   => "",
        "AccessMethod"   => "Coordinator_Inscriptions_Access_Has",
      ),
     "RegGroups" => array
     (
        "Href"     => "",
        "HrefArgs" => "ModuleName=RegGroups&Action=EditList",
        "Name"    => "Grupos Vis&iacute;veis do Cadastro",
        "Name_UK"     => "Visible Registration Groups",
        "Title"    => "Grupos Vis&iacute;veis do Cadastro",
        "Title_UK"     => "Visible Registration Groups",
        "Public"   => 1,
        "Person"   => 1,
        "Admin"   => 1,
        "Distributor"   => 1,
        "Coordinator"   => 1,
        "Teacher"   => 1,
        "Handler"   => "",
        "AccessMethod"   => "Coordinator_Inscriptions_Access_Has",
      ),
);
