array
(
   "ID" => array
   (
      "Admin" => 1,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "ID",
      "Name_ES" => "ID",
      "Name_UK" => "ID",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "ID",
      "ShortName_ES" => "ID",
      "ShortName_UK" => "ID",
      "Sql" => "INT NOT NULL PRIMARY KEY AUTO_INCREMENT",
      "Title" => "ID",
      "Title_ES" => "ID",
      "Title_UK" => "ID",
   ),
   "SystemURL" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      
      "Name" => "URL do App",
      "Name_ES" => "URL del App",
      "Name_UK" => "App URL",
      
      "Person" => 1,
      "Public" => 1,
      "Search" => False,

      "Size" => "30x1",
      "Sql" => "VARCHAR(256)",
   ),
   "Status" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Default" => 2,
      "Friend" => 1,
      "Name" => "Status",
      "Name_ES" => "Status",
      "Name_UK" => "Status",
      "Person" => 1,
      "Public" => 1,
      "Search" => True,
      "SearchCheckBox" => 1,
      "SearchDefault" => 2,
      "ShortName" => "Status",
      "ShortName_ES" => "Status",
      "ShortName_UK" => "Status",
      "Size" => "10",
      "Sql" => "ENUM",
      "Title" => "Status",
      "Title_ES" => "Status",
      "Title_UK" => "Status",
      "Values" => array("Não","Sim"),
      "Values_UK" => array("No","Yes"),
      "Values_ES" => array("No","Sin"),
   ),
   "Online" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      
      "Name" => "Entidade Online",
      "Name_ES" => "Entidad Online",
      "Name_UK" => "Entity Online",
      
      "Person" => 1,
      "Public" => 1,
      "Search" => True,

      "Sql" => "ENUM",
      "Values" => array("Sim","Não"),
      "Values_UK" => array("Yes","No"),
      "Values_ES" => array("Sin","No"),
      "Default" => 1,
   ),
   "Online_Message" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      
      "Name" => "Mensagem, Offline",
      "Name_ES" => "Mensaje, Offline",
      "Name_UK" => "Offline Message",
      
      "Person" => 1,
      "Public" => 1,
      "Search" => False,

      "Sql" => "VARCHAR(256)",
      "Default" => "Temporarily Offline due to system maintainance",
   ),
   "Initials" => array
   (
      "Admin" => 2,
      "Assessor" => 0,
      "Compulsory" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      
      "Name" => "Sigla",
      "Name_ES" => "Sigla",
      "Name_UK" => "Initials",
      "Person" => 1,
      "Public" => 1,
      
      "Search" => False,
      "ShortName" => "Sigla",
      "ShortName_ES" => "Sigla",
      "ShortName_UK" => "Initials",
      "Size" => "8",
      "Sql" => "VARCHAR(64)",
      "Title" => "Sigla",
      "Title_ES" => "Sigla",
      "Title_UK" => "Initials",
   ),
   "Name" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Compulsory" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "Nome",
      "Name_ES" => "Nome",
      "Name_UK" => "Name",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Nome",
      "ShortName_ES" => "Nome",
      "ShortName_UK" => "Name",
      
      "Size" => "25",
      "Sql" => "VARCHAR(255)",
      "Title" => "Nome",
      "Title_ES" => "Nome",
      "Title_UK" => "Name",
      "Search_Joined" => array("Title","Initials"),
      "Search" => True,
   ),
   "Title" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Compulsory" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "Título",
      "Name_ES" => "Título",
      "Name_UK" => "Title",
      "Person" => 1,
      "Public" => 1,
      "Search" => True,
      "ShortName" => "Título",
      "ShortName_ES" => "Título",
      "ShortName_UK" => "Title",
      "Size" => "50",
      "Sql" => "VARCHAR(255)",
      "Title" => "Título",
      "Title_ES" => "Título",
      "Title_UK" => "Title",
   ),
   "State" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "UF",
      "Name_ES" => "UF",
      "Name_UK" => "State",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "UF",
      "ShortName_ES" => "UF",
      "ShortName_UK" => "State",
      "Size" => "50",
      "Sql" => "ENUM",
      "Title" => "UF",
      "Title_ES" => "UF",
      "Title_UK" => "State",
      "Values" => array(""),
   ),
   "Address" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "EditIDCols" => array(""),
      "Friend" => 1,
      "Name" => "Endereço",
      "Name_ES" => "Endereço",
      "Name_UK" => "Address",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Endereço",
      "ShortName_ES" => "Endereço",
      "ShortName_UK" => "Address",
      "ShowIDCols" => array(""),
      "Size" => "50",
      "Sql" => "VARCHAR(255)",
      "Title" => "Endereço",
      "Title_ES" => "Endereço",
      "Title_UK" => "Address",
   ),
   "Phone" => array
(
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "Fone",
      "Name_ES" => "Fone",
      "Name_UK" => "Phone",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Fone",
      "ShortName_ES" => "Fone",
      "ShortName_UK" => "Phone",
      "Size" => "15",
      "Sql" => "VARCHAR(255)",
      "Title" => "Fone",
      "Title_ES" => "Fone",
      "Title_UK" => "Phone",
   ),
   "Fax" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "Fax",
      "Name_ES" => "Fax",
      "Name_UK" => "Fax",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Fax",
      "ShortName_ES" => "Fax",
      "ShortName_UK" => "Fax",
      "Size" => "15",
      "Sql" => "VARCHAR(255)",
      "Title" => "Fax",
      "Title_ES" => "Fax",
      "Title_UK" => "Fax",
   ),
   "Url" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "HRefIt" => 1,
      "Name" => "Site Oficial",
      "Name_ES" => "Site Oficial",
      "Name_UK" => "Official Website",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Site Oficial",
      "ShortName_ES" => "Site Oficial",
      "ShortName_UK" => "Official Website",
      "Size" => "15",
      "Sql" => "VARCHAR(255)",
      "Title" => "Site Oficial",
      "Title_ES" => "Site Oficial",
      "Title_UK" => "Official Website",
   ),
   "Email" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "Email Oficial",
      "Name_ES" => "Email Oficial",
      "Name_UK" => "Official Email",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Email Oficial",
      "ShortName_ES" => "Email Oficial",
      "ShortName_UK" => "Official Email",
      "Size" => "25",
      "Sql" => "VARCHAR(255)",
      "Title" => "Email Oficial",
      "Title_ES" => "Email Oficial",
      "Title_UK" => "Official Email",
   ),
   "City" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "Cidade",
      "Name_ES" => "Cidade",
      "Name_UK" => "City",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Cidade",
      "ShortName_ES" => "Cidade",
      "ShortName_UK" => "City",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Title" => "Cidade",
      "Title_ES" => "Cidade",
      "Title_UK" => "City",
   ),
   "Area" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "Bairro",
      "Name_ES" => "Bairro",
      "Name_UK" => "Area",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Bairro",
      "ShortName_ES" => "Bairro",
      "ShortName_UK" => "Area",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Title" => "Bairro",
      "Title_ES" => "Bairro",
      "Title_UK" => "Area",
   ),
   "ZIP" => array
   (
      "Admin" => 2,
      "Assessor" => 1,
      "Coordinator" => 1,
      "Friend" => 1,
      "Name" => "CEP",
      "Name_ES" => "CEP",
      "Name_UK" => "ZIP",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "CEP",
      "ShortName_ES" => "CEP",
      "ShortName_UK" => "ZIP",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Title" => "CEP",
      "Title_ES" => "CEP",
      "Title_UK" => "ZIP",
   ),
   "HtmlIcon1" => array
   (
      "Admin" => 2,
      "Coordinator" => 1,
      "Extensions" => array("jpg","png"),
      "Iconify" => 1,
      "Name" => "Ícone Esquerda (HTML)",
      "Name_ES" => "Ícone Esquerda (HTML)",
      "Name_UK" => "Left Icon (HTML)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Ícone Esquerda (HTML)",
      "ShortName_ES" => "Ícone Esquerda (HTML)",
      "ShortName_UK" => "Left Icon (HTML)",
      "Size" => "25",
      "Sql" => "FILE",
      "Title" => "Ícone Esquerda (HTML)",
      "Title_ES" => "Ícone Esquerda (HTML)",
      "Title_UK" => "Left Icon (HTML)",
   ),
   "HtmlIcon2" => array
   (
      "Admin" => 2,
      "Coordinator" => 1,
      "Extensions" => array("jpg","png"),
      "Iconify" => 1,
      "Name" => "Ícone Direita (HTML)",
      "Name_ES" => "Ícone Direita (HTML)",
      "Name_UK" => "Right Icon (HTML)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Ícone Direita (HTML)",
      "ShortName_ES" => "Ícone Direita (HTML)",
      "ShortName_UK" => "Right Icon (HTML)",
      "Size" => "25",
      "Sql" => "FILE",
      "Title" => "Ícone Direita (HTML)",
      "Title_ES" => "Ícone Direita (HTML)",
      "Title_UK" => "Right Icon (HTML)",
   ),
   "LatexIcon1" => array
   (
      "Admin" => 2,
      "Coordinator" => 1,
      "Extensions" => array("jpg","png"),
      "Iconify" => 1,
      "Name" => "Ícone Esquerda (LaTeX)",
      "Name_ES" => "Ícone Esquerda (LaTeX)",
      "Name_UK" => "Left Icon (LaTeX)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Ícone Esquerda (LaTeX)",
      "ShortName_ES" => "Ícone Esquerda (LaTeX)",
      "ShortName_UK" => "Left Icon (LaTeX)",
      "Size" => "25",
      "Sql" => "FILE",
      "Title" => "Ícone Esquerda (LaTeX)",
      "Title_ES" => "Ícone Esquerda (LaTeX)",
      "Title_UK" => "Left Icon (LaTeX)",
   ),
   "LatexIcon2" => array
   (
      "Admin" => 2,
      "Coordinator" => 1,
      "Extensions" => array("jpg","png"),
      "Iconify" => 1,
      "Name" => "Ícone Direita (LaTeX)",
      "Name_ES" => "Ícone Direita (LaTeX)",
      "Name_UK" => "Right Icon (LaTeX)",
      "Person" => 1,
      "Public" => 1,
      "ShortName" => "Ícone Direita (LaTeX)",
      "ShortName_ES" => "Ícone Direita (LaTeX)",
      "ShortName_UK" => "Right Icon (LaTeX)",
      "Size" => "25",
      "Sql" => "FILE",
      "Title" => "Ícone Direita (LaTeX)",
      "Title_ES" => "Ícone Direita (LaTeX)",
      "Title_UK" => "Right Icon (LaTeX)",
   ),
);

