array
(
   "Auth" => array
   (
      "Name" => "Autentifição",
      "Name_UK" => "Authentication",
      "Size" => "10",
      "Sql" => "ENUM",
      "Values" => array("Não","Sim"),
      "Values_UK" => array("No","Yes"),
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
      "Default"  => 2,
   ),
   "Secure" => array
   (
      "Name" => "Seguro (SSL)",
      "Name_UK" => "Secure (SSL)",

      "Sql" => "ENUM",
      "Values" => array("Nenhum","SSL","TSL"),
      "Values_UK" => array("None","SSL","TSL"),
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
      "Default"  => 2,
   ),
   "Port" => array
   (
      "Name" => "Porta",
      "Name_UK" => "Port",
      "Size" => 3,
      "Sql" => "VARCHAR(8)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
      "Default"  => 465,
      "Regex"  => '^\d+$',
   ),
   "Host" => array
   (
      "Name" => "Servidor SMTP",
      "Name_UK" => "SWMTP Server",
      "Size" => 25,
      "Sql" => "VARCHAR(256)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
      "Default"  => 'smtp.gmail.com',
   ),
   "User" => array
   (
      "Name" => "User",
      "Name_UK" => "Usuário",
      "Size" => 25,
      "Sql" => "VARCHAR(256)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
      "Default"  => 'foo@gmail.com',
   ),
   "Password" => array
   (
      "Name" => "Senha",
      "Name_UK" => "Password",
      "Size" => 15,
      "Sql" => "VARCHAR(256)",
      "Password" => 1,
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
   ),
   "FromEmail" => array
   (
      "Name" => "Email Origem",
      "Name_UK" => "From Email",
      "Size" => 25,
      "Sql" => "VARCHAR(256)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
   ),
   "FromName" => array
   (
      "Name" => "Nome Origem",
      "Name_UK" => "From Name",
      "Size" => 25,
      "Sql" => "VARCHAR(256)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
   ),
   "ReplyTo" => array
   (
      "Name" => "Responder Para",
      "Name_UK" => "Reply To",
      "Size" => 25,
      "Sql" => "VARCHAR(256)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
   ),
   "BCCEmail" => array
   (
      "Name" => "BCC Para",
      "Name_UK" => "CCO To",
      "Size" => 25,
      "Sql" => "VARCHAR(256)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"    => 2,
      "Coordinator" => 1,
      "Search"  => FALSE,
      "Compulsory"  => TRUE,
   ),
);
