array
(
   "Auth" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Default" => "2",
      "Name" => "Autentifição",
      "Name_ES" => "Autentifição",
      "Name_UK" => "Authentication",
      "Person" => "0",
      "Public" => "0",
      "Search" => "",
      "ShortName" => "Autentifição",
      "ShortName_ES" => "Autentifição",
      "ShortName_UK" => "Authentication",
      "Size" => "10",
      "Sql" => "ENUM",
      "Title" => "Autentifição",
      "Title_ES" => "Autentifição",
      "Title_UK" => "Authentication",
      "Values" => array("Não","Sim"),
      "Values_UK" => array("No","Yes"),
   ),
   "Secure" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Default" => "2",
      "Name" => "Seguro (SSL)",
      "Name_ES" => "Seguro (SSL)",
      "Name_UK" => "Secure (SSL)",
      "Person" => "0",
      "Public" => "0",
      "Search" => "",
      "ShortName" => "Seguro (SSL)",
      "ShortName_ES" => "Seguro (SSL)",
      "ShortName_UK" => "Secure (SSL)",
      "Sql" => "ENUM",
      "Title" => "Seguro (SSL)",
      "Title_ES" => "Seguro (SSL)",
      "Title_UK" => "Secure (SSL)",
      "Values" => array("Nenhum","SSL","TSL"),
      "Values_UK" => array("None","SSL","TSL"),
   ),
   "Port" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Default" => "465",
      "Name" => "Porta",
      "Name_ES" => "Porta",
      "Name_UK" => "Port",
      "Person" => "0",
      "Public" => "0",
      "Regex" => "^\d+$",
      "Search" => "",
      "ShortName" => "Porta",
      "ShortName_ES" => "Porta",
      "ShortName_UK" => "Port",
      "Size" => "3",
      "Sql" => "VARCHAR(8)",
      "Title" => "Porta",
      "Title_ES" => "Porta",
      "Title_UK" => "Port",
   ),
   "Host" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Default" => "smtp.gmail.com",
      "Name" => "Servidor SMTP",
      "Name_ES" => "Servidor SMTP",
      "Name_UK" => "SMTP Server",
      "Person" => "0",
      "Public" => "0",
      "Search" => "",
      "ShortName" => "Servidor SMTP",
      "ShortName_ES" => "Servidor SMTP",
      "ShortName_UK" => "SMTP Server",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Title" => "Servidor SMTP",
      "Title_ES" => "Servidor SMTP",
      "Title_UK" => "SMTP Server",
   ),
   "User" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Default" => "foo@gmail.com",
      "Name" => "User",
      "Name_ES" => "User",
      "Name_UK" => "Usuário",
      "Person" => "0",
      "Public" => "0",
      "Search" => "",
      "ShortName" => "User",
      "ShortName_ES" => "User",
      "ShortName_UK" => "Usuário",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Title" => "User",
      "Title_ES" => "User",
      "Title_UK" => "Usuário",
   ),
   "Password" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Name" => "Senha",
      "Name_ES" => "Senha",
      "Name_UK" => "Password",
      "Password" => "1",
      "Person" => "0",
      "Public" => "0",
      "Search" => "",
      "ShortName" => "Senha",
      "ShortName_ES" => "Senha",
      "ShortName_UK" => "Password",
      "Size" => "15",
      "Sql" => "VARCHAR(256)",
      "Title" => "Senha",
      "Title_ES" => "Senha",
      "Title_UK" => "Password",
   ),
   "FromEmail" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Name" => "Email Origem",
      "Name_ES" => "Email Origem",
      "Name_UK" => "From Email",
      "Person" => "0",
      "Public" => "0",
      "Search" => "",
      "ShortName" => "Email Origem",
      "ShortName_ES" => "Email Origem",
      "ShortName_UK" => "From Email",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Title" => "Email Origem",
      "Title_ES" => "Email Origem",
      "Title_UK" => "From Email",
   ),
   "FromName" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Name" => "Nome Origem",
      "Name_ES" => "Nome Origem",
      "Name_UK" => "From Name",
      "Person" => "0",
      "Public" => "0",
      "Search" => "",
      "ShortName" => "Nome Origem",
      "ShortName_ES" => "Nome Origem",
      "ShortName_UK" => "From Name",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Title" => "Nome Origem",
      "Title_ES" => "Nome Origem",
      "Title_UK" => "From Name",
   ),
   "ReplyTo" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Name" => "Responder Para",
      "Name_ES" => "Responder Para",
      "Name_UK" => "Reply To",
      "Person" => "0",
      "Public" => "0",
      "Search" => "",
      "ShortName" => "Responder Para",
      "ShortName_ES" => "Responder Para",
      "ShortName_UK" => "Reply To",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Title" => "Responder Para",
      "Title_ES" => "Responder Para",
      "Title_UK" => "Reply To",
   ),
   "BCCEmail" => array
   (
      "Admin" => "2",
      "Compulsory" => "1",
      "Coordinator" => "1",
      "Name" => "BCC Para",
      "Name_ES" => "BCC Para",
      "Name_UK" => "CCO To",
      "Person" => "0",
      "Public" => "0",
      "Search" => "",
      "ShortName" => "BCC Para",
      "ShortName_ES" => "BCC Para",
      "ShortName_UK" => "CCO To",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Title" => "BCC Para",
      "Title_ES" => "BCC Para",
      "Title_UK" => "CCO To",
   ),
);

