array
(
   "ID" => array
   (
      "Name" => "ID",
      "Sql" => "INT NOT NULL PRIMARY KEY AUTO_INCREMENT",
      "Public"   => 1,
      "Person"   => 1,
      "Admin"    => 1,
      "Friend"     => 1,
      "Coordinator" => 1,
      "Distributor" => 1,
      "Assessor"  => 1,
   ),
   "Status" => array
   (
      "Name" => "Ativo",
      "Size" => "10",
      "Sql" => "ENUM",
      "Values" => array("Não","Sim"),
      "Values_UK" => array("No","Yes"),
      "SearchDefault"   => 2,
      "Default"   => 2,
      "Public"   => 1,
      "Person"   => 1,
      "Admin"    => 2,
      "Friend"     => 1,
      "Coordinator" => 1,
      "Distributor" => 2,
      "Assessor"  => 1,
      "Search"  => TRUE,
      "SearchCheckBox"  => TRUE,
   ),
   "Initials" => array
   (
      "Name" => "Sigla",
      "Name_UK" => "Initials",
      "Size" => "3",
      "Sql" => "VARCHAR(8)",
      "Public"   => 1,
      "Person"   => 1,
      "Admin"    => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
      "Search"  => TRUE,
      "Compulsory"  => TRUE,
   ),
   "Name" => array
   (
      "Name" => "Nome",
      "Name_UK" => "Name",
      "Size" => "25",
      "Sql" => "VARCHAR(255)",
      "Public"   => 1,
      "Person"   => 1,
      "Admin"    => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
      "Search"  => TRUE,
      "Compulsory"  => TRUE,
   ),
   "Title" => array
   (
      "Name" => "Título",
      "Name_UK" => "Title",
      "Size" => "50",
      "Sql" => "VARCHAR(255)",
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
      "Search"  => TRUE,
      "Compulsory"  => TRUE,
   ),
   "State" => array
   (
      "Name" => "UF",
      "Name_UK" => "State",
      "Size" => "50",
      "Sql" => "ENUM",
      "Values" => array(),
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
   ),
   "Address" => array
   (
      "Name" => "Endereço",
      "Name_UK" => "Address",
      "Size" => "50",
      "Sql" => "VARCHAR(255)",
      "ShowIDCols" => array(""),
      "EditIDCols" => array(""),
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Distributor" => 2,
      "Coordinator" => 2,
      "Assessor"  => 1,
   ),
   "Phone" => array
   (
      "Name" => "Fone",
      "Name_UK" => "Phone",
      "Size" => "15",
      "Sql" => "VARCHAR(255)",
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
   ),
   "Fax" => array
   (
      "Name" => "Fax",
      "Name_UK" => "Fax",
      "Size" => "15",
      "Sql" => "VARCHAR(255)",
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
   ),
   "Url" => array
   (
      "HRefIt" => TRUE,
      "Name" => "Site Oficial",
      "Name_UK" => "Official Website",
      "Size" => "15",
      "Sql" => "VARCHAR(255)",
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
   ),
   "Email" => array
   (
      "Name" => "Email Oficial",
      "Name_UK" => "Official Email",
      "Size" => "25",
      "Sql" => "VARCHAR(255)",
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
   ),
   "City" => array
   (
      "Name" => "Cidade",
      "Name_UK" => "City",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
   ),
   "Area" => array
   (
      "Name" => "Bairro",
      "Name_UK" => "Area",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
   ),
   "ZIP" => array
   (
      "Name" => "CEP",
      "Name_UK" => "ZIP",
      "Size" => "25",
      "Sql" => "VARCHAR(256)",
      "Public" => 1,
      "Person"   => 1,
      "Admin" => 2,
      "Friend"     => 1,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Assessor"  => 1,
   ),
   "HtmlIcon1" => array
   (
      "Name" => "Ícone Esquerda (HTML)",
      "Name_UK" => "Left Icon (HTML)",
      "Size" => "25",
      "Sql" => "FILE",
      "Public" => 1,
      "Person" => 1,
      "Admin" => 2,
      "Coordinator" => 2,
      "Extensions" => array("jpg","png"),
      "Iconify" => TRUE,
   ),
   "HtmlIcon2" => array
   (
      "Name" => "Ícone Direita (HTML)",
      "Name_UK" => "Right Icon (HTML)",
      "Size" => "25",
      "Sql" => "FILE",
      "Public" => 1,
      "Person" => 1,
      "Admin" => 2,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Extensions" => array("jpg","png"),
      "Iconify" => TRUE,
   ),
   "LatexIcon1" => array
   (
      "Name" => "Ícone Esquerda (LaTeX)",
      "Name_UK" => "Left Icon (LaTeX)",
      "Size" => "25",
      "Sql" => "FILE",
      "Public" => 1,
      "Person" => 1,
      "Admin" => 2,
      "Coordinator" => 2,
      "Distributor" => 2,
      "Extensions" => array("jpg","png"),
      "Iconify" => TRUE,
   ),
   "LatexIcon2" => array
   (
      "Name" => "Ícone Direita (LaTeX)",
      "Name_UK" => "Right Icon (LaTeX)",
      "Size" => "25",
      "Sql" => "FILE",
      "Public" => 1,
      "Person" => 1,
      "Admin" => 2,
      "Coordinator" => 2,
      "Extensions" => array("jpg","png"),
      "Iconify" => TRUE,
   ),
);
