array
(
   "1_ShowUnit" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&ModuleName=Units&Action=Show&ID=".$this->Unit("ID"),
      "Name" => "Entidade",
      "Name_ES" => "Entidad",
      "Name_UK" => "Department",
      "OmitArgs" => array("Event"),
      "Person" => "0",
      "Public" => "1",
      "ShortName" => "Entidade",
      "ShortName_ES" => "Entidad",
      "ShortName_UK" => "Department",
      "Title" => "Dados, Entidade Acadêmica",
      "Title_ES" => "Dados, Entidad Academica",
      "Title_UK" => "Department",
   ),
   "2_Friends" => array
   (
      "Admin" => "1",
      "Assessor" => "0",
      "Coordinator" => "1",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&ModuleName=Friends&Action=Search",
      "Name" => "Cadastros",
      "Name_ES" => "Registros",
      "Name_UK" => "Registrations",
      "OmitArgs" => array("Event"),
      "Person" => "0",
      "Public" => "0",
      "ShortName" => "Cadastros",
      "ShortName_ES" => "Registros",
      "ShortName_UK" => "Registrations",
      "Title" => "Cadastros",
      "Title_ES" => "Registros",
      "Title_UK" => "Registrations",
   ),
   "3_Events" => array
   (
      "Admin" => "1",
      "Assessor" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&ModuleName=Events&Action=Search",
      "Name" => "Eventos",
      "Name_ES" => "Eventos",
      "Name_UK" => "Events",
      "OmitArgs" => array("Event"),
      "Person" => "0",
      "Public" => "1",
      "ShortName" => "Eventos",
      "ShortName_ES" => "Eventos",
      "ShortName_UK" => "Events",
      "Title" => "Eventos",
      "Title_ES" => "Eventos",
      "Title_UK" => "Events",
   ),
   "4_Permissions" => array
   (
      "Admin" => "1",
      "Coordinator" => "1",
      "Friend" => "0",
      "Href" => "?Unit=".$this->Unit("ID")."&ModuleName=Permissions&Action=Search",
      "Name" => "Permissões",
      "Name_ES" => "Permisos",
      "Name_UK" => "Permissions",
      "OmitArgs" => array("Event"),
      "Person" => "0",
      "Public" => "0",
      "ShortName" => "Permissões",
      "ShortName_ES" => "Permisos",
      "ShortName_UK" => "Permissions",
      "Title" => "Gerenciar Permissões",
      "Title_ES" => "Permisos",
      "Title_UK" => "Manage Permissions",
   ),
   "5_Uploads" => array
   (
      "Admin" => "1",
      "Advisor" => "0",
      "Coordinator" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Action=Uploads",
      "Monitor" => "0",
      "Name" => "Uploads",
      "Name_ES" => "Uploads",
      "Name_UK" => "Uploads",
      "OmitArgs" => array("Event"),
      "Person" => "0",
      "Public" => "0",
      "ShortName" => "Uploads",
      "ShortName_ES" => "Uploads",
      "ShortName_UK" => "Uploads",
      "Title" => "Gerenciar Uploads",
      "Title_ES" => "Uploads",
      "Title_UK" => "Manage Uploads",
   ),
);

